# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qlyrxDialog
                                 A QGIS plugin
 Apply Arcgis Pro .lyrx style
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-09
        git sha              : $Format:%H$
        copyright            : (C) 2019 by arc2qgis
        email                : dror.bogin@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os



class qlyrxStyler():
    def __init__(self, parent=None):
        
        self.capStyles = {"Round" : 32, "Square" : 1, "Butt": 0}
        self.joinStyles = {"Miter": 0, "Bevel" : 64, "Round": 128}
        self.point2mm =  0.352778
        self.paths_to_shapes_array = {
            "Cross2" : {"paths" : [
                [[-0.5,0.5],[0.5,-0.5]],
                [[-0.5,-0.5],[0.5,0.5]]
            ]},
            "Line" : {"paths" : [
                [[3,0],[-3,0]]
            ]
            }
        }

        self.circle_rings = {
                            "curveRings" : [
                            [[1.2246467991473532e-16,2],
                                {
                                "a" : [[1.2246467991473532e-16,2],
                                    [0,0],[0,1]]
                                }]
                            ]
                        }
        
